on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: wangyoucao577/go-release-action@8fa1e8368c8465264d64e0198208e10f71474c87 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
          goversion: 1.22.3
          ldflags: -s
          asset_name: tpc
          compress_assets: OFF
          md5sum: true
          sha256sum: true
          extra_files: SII_Decrypt.exe
